name: intel-iotg-kernel
version: 5.15.0-1000.0.0
summary: generic linux kernel
description: The Intel IoTG Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core20

parts:
  kernel:
    source: git://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    make-parameters:
      - KERNEL_SOURCE=focal:linux-uc20-inteli-iotg
      - KERNEL=linux-image-uc20-intel-iotg
      - KERNEL_IMAGE_FORMAT=efi
      - PROPOSED=true
    build-packages:
      - debootstrap
      - gnupg
      - kmod
      - lsb-release
