name: pc-kernel
version: 5.3.0-24.26
summary: generic linux kernel
description: The generic Ubuntu kernel package as a snap
type: kernel
confinement: strict

parts:
  kernel:
    source: https://git.launchpad.net/~ubuntu-kernel/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    make-parameters:
      - KERNEL_SERIES=focal
      - KERNEL_SOURCE=linux
      - KERNEL=linux-pc-image
      - PROPOSED=true
    build-packages:
      - debootstrap
      - lsb-release
