name: pc-kernel
version: 5.4.0-15.18
summary: generic linux kernel
description: The generic Ubuntu kernel package as a snap
type: kernel
confinement: strict

parts:
  kernel:
    source: git://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    make-parameters:
      - KERNEL_SOURCE=focal:linux
      - KERNEL=linux-pc-image
      - PROPOSED=true
    build-packages:
      - debootstrap
      - lsb-release
