name: intel-kernel
version: 5.13.0-1007.7.2
summary: generic linux kernel
description: The Intel Ubuntu kernel package as a snap
type: kernel
confinement: strict
build-base: core20

parts:
  kernel:
    source: git://git.launchpad.net/~canonical-kernel-snaps/+git/kernel-snaps-uc20
    source-type: git
    source-branch: master
    plugin: make
    make-parameters:
      - KERNEL_SOURCE=focal:linux-uc20-intel
      - KERNEL=linux-image-uc20-intel
      - KERNEL_IMAGE_FORMAT=efi
      - PROPOSED=true
    build-packages:
      - debootstrap
      - gnupg
      - kmod
      - lsb-release
